# Generated by Django 3.2.6 on 2021-09-01 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_advisory', models.CharField(max_length=255)),
                ('advisory_level', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitute', models.CharField(max_length=50)),
                ('longtittude', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('pending', 'Pending')], default='published', max_length=10),
        ),
    ]
