# Generated by Django 3.2.6 on 2021-09-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210901_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='location_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
